# Generated by Django 3.2.6 on 2021-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('subtitle', models.CharField(max_length=180, null=True)),
                ('body', models.TextField()),
                ('slug', models.SlugField(default=None, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title_image_url_1', models.URLField(blank=True, max_length=1024, null=True)),
                ('content_image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_image_url_1', models.URLField(blank=True, max_length=1024, null=True)),
                ('content_image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_image_url_2', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
