# Generated by Django 3.2.6 on 2021-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210821_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
